services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: cash-flow-frontend-devstand-app
    restart: unless-stopped
    env_file:
      - .production.env
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - '3001:80'
    networks:
      - cash-flow-network

networks:
  cash-flow-network:
    external: true
